version: '2'
services:
 ecshop:
   image: vulhub/ecshop:4.0.6
   container_name: ecshop
   depends_on:
    - ecshop_mysql
   ports:
    - "8510:80"
 ecshop_mysql:
   image: mysql:5.5
   container_name: ecshop_mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=root
 phpmyadmin:
   image: vulhub/phpmyadmin:4.8.1
   container_name: phpmyadmin
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8511:80"
   depends_on:
    - mysql
 mysql:
   image: mysql:5.5
   container_name: phpmyadmin_mysql
   environment: 
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
 apache:
   build: ./apache2.4.49
   ports:
    - "8512:80"
