version: '2'
services:
 october:
   image: php:7.0-apache
   container_name: october
   hostname: october
   volumes:
    - ./october:/var/www/html/october
   ports:
    - "8511:80"
   depends_on:
    - october_mysql
 october_mysql:
   image: mysql:5.5
   container_name: october_mysql
   hostname: october_mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=tuesday
    - MYSQL_DATABASE=october
    - MYSQL_USER=octuser
    - MYSQL_PASSWORD=friday
 apache:
   build: ./apache2.4.49
   container_name: apache2
   hostname: apache2
   volumes:
    - ./apache2.4.49/robots.txt:/var/www/html/robots.txt
    - ./apache2.4.49/peanutbutterandjelly:/var/www/html/peanutbutterandjelly
   ports:
    - "8512:80"
 wordpress:
   build: ./wordpress
   container_name: wordpress
   hostname: wp
   ports:
     - "8514:80"
   environment:
     WORDPRESS_DB_PASSWORD: password
   volumes:
     - "wp:/var/www/html:rw"
     - ./wordpress/wp-config.php:/var/www/html/wp-config.php
 mysql:
   image: "mysql:5.7"
   container_name: mysql
   hostname: wpMysql
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: wordpress
   volumes:
     - db:/var/lib/mysql
 st_mysql:
    image: mysql:5.5
    container_name: st_mysql
    hostname: st_mysql
    restart: unless-stopped
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=sploitme
      - MYSQL_DATABASE=payroll
      - MYSQL_PORT=3306
    volumes:
      - ./startrek_payroll/mysql/startrek_payroll.sql:/docker-entrypoint-initdb.d/startrek_payroll.sql
#    networks:
#      - backend
 php:
    image: php:8.0-fpm
    container_name: php
    hostname: php
    restart: unless-stopped
    build:
      context: startrek_payroll/php
      dockerfile: Dockerfile
    depends_on:
      - st_mysql
    volumes:
      - ./startrek_payroll/app:/app
#    networks:
#      - backend
 nginx:
    image: nginx:stable-alpine
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    depends_on:
      - st_mysql
      - php
    ports:
      - "8515:80"
    volumes:
      - ./startrek_payroll/app:/app
      - ./startrek_payroll/nginx/site.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - frontend
#      - backend
volumes:
  wp: {}
  db: {}
#networks:
#  frontend:
#    driver: bridge
#  backend:
#    driver: bridge
