version: '2'
services:
 phpmyadmin:
   image: vulhub/phpmyadmin:4.8.1
   container_name: phpmyadmin
   hostname: phpmyadmin4_8
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8511:80"
   depends_on:
    - mysql
 phpmyadmin_mysql:
   image: mysql:5.5
   container_name: phpmyadmin_mysql
   hostname: pypmyadmin4_8Mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=tuesday
    - MYSQL_DATABASE=phpmyadmin
    - MYSQL_USER=dory
    - MYSQL_PASSWORD=nemo
    - MYSQL_DATABASE=mtgas
    - MYSQL_USER=mtgas
    - MYSQL_PASSWORD=ugly
 apache:
   build: ./apache2.4.49
   container_name: apache2
   hostname: apache2
   ports:
    - "8512:80"
 wordpress:
   build: ./wordpress
   container_name: wordpress
   hostname: wp
   ports:
     - "8514:80"
   environment:
     WORDPRESS_DB_PASSWORD: thursday
   volumes:
     - "wp:/var/www/html:rw"
 wordpress_mysql:
   image: "mysql:5.7"
   container_name: wordpress_mysql
   hostname: wpMysql
   environment:
     MYSQL_ROOT_PASSWORD: wednesday
     MYSQL_DATABASE: wordpress
     MYSQL_USER: dory
     MYSQL_PASSWORD: nemo
     MYSQL_DATABASE: credz
   volumes:
     - db:/var/lib/mysql
 wp_phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   container_name: wordpress_phpmyadmin
   hostname: wpMysql
   ports:
     - 8515:80
   environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mysql
   depends_on:
     - wordpress_mysql
volumes:
  wp: {}
  db: {}
