version: '2'
services:
 phpmyadmin:
   image: vulhub/phpmyadmin:4.8.1
   container_name: phpmyadmin
   hostname: phpmyadmin4_8
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8511:80"
   depends_on:
    - mysql
 phpmyadmin_mysql:
   image: mysql:5.5
   container_name: phpmyadmin_mysql
   hostname: pypmyadmin4_8Mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=tuesday
    - MYSQL_DATABASE=phpmyadmin
    - MYSQL_USER=dory
    - MYSQL_PASSWORD=nemo
    - MYSQL_DATABASE=mtgas
    - MYSQL_USER=mtgas
    - MYSQL_PASSWORD=ugly
 apache:
   build: ./apache2.4.49
   container_name: apache2
   hostname: apache2
   ports:
    - "8512:80"
 wordpress:
   build: ./wordpress
   container_name: wordpress
   hostname: wp
   ports:
     - "8514:80"
   environment:
     WORDPRESS_DB_PASSWORD: thursday
   volumes:
     - "wp:/var/www/html:rw"
 wordpress_mysql:
   image: "mysql:5.7"
   container_name: wordpress_mysql
   hostname: wpMysql
   environment:
     MYSQL_ROOT_PASSWORD: wednesday
     MYSQL_DATABASE: wordpress
     MYSQL_USER: dory
     MYSQL_PASSWORD: nemo
     MYSQL_DATABASE: credz
   volumes:
     - db:/var/lib/mysql
 st_mysql:
    image: mysql:5.5
    container_name: st_mysql
    hostname: st_mysql
    restart: unless-stopped
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=sploitme
      - MYSQL_DATABASE=payroll
      - MYSQL_DATABASE=credz
      - MYSQL_PORT=3306
    volumes:
      - ./mysql/startrek_payroll.sql:/docker-entrypoint-initdb.d/startrek_payroll.sql
 st_php:
    image: php:8.0-fpm
    container_name: st_php
    hostname: st_php
    restart: unless-stopped
    build:
      context: php
      dockerfile: Dockerfile
    depends_on:
      - st_mysql
    volumes:
      - ./startrek_payroll/app:/app
 st_nginx:
    image: nginx:stable-alpine
    container_name: st_nginx
    hostname: st_nginx
    restart: unless-stopped
    depends_on:
      - st_mysql
      - st_php
    ports:
      - "8515:80"
    volumes:
      - ./startrek_payroll/app:/app
      - ./startrek_payroll/nginx/site.conf:/etc/nginx/conf.d/default.conf
volumes:
  wp: {}
  db: {}
