version: '2'
services:
 ecshop:
   image: vulhub/ecshop:4.0.6
   container_name: ecshop
   depends_on:
    - ecshop_mysql
   ports:
    - "8510:80"
 ecshop_mysql:
   image: mysql:5.5
   container_name: ecshop_mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=root
 phpmyadmin:
   image: vulhub/phpmyadmin:4.8.1
   container_name: phpmyadmin
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8511:80"
   depends_on:
    - mysql
 phpmyadmin_mysql:
   image: mysql:5.5
   container_name: phpmyadmin_mysql
   environment: 
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
 apache:
   build: ./apache2.4.49
   container_name: apache2
   ports:
    - "8512:80"
 drupal:
   image: vulhub/drupal:7.31
   container_name: drupal
   depends_on:
    - drupal_mysql
   ports:
    - "8513:80"
 drupal_mysql:
   image: mysql:5.5
   container_name: drupal_mysql
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal
 wordpress:
    build: ./wordpress
    ports:
      - "8514:80"
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - "wp:/var/www/html:rw"
 wordpress_mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
 phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8515:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - wordpress_mysql
volumes:
  wp: {}
  db: {}
